version: '3'
services:
  web:
    build: .
    volumes:
      - app_bundler_data:/app/vendor/
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:11.6-alpine
    volumes:
      - postgresql_data

volumes:
  app_bundler_data:
  postgresql_data: